-- 2024-09-28 init migration for JP Digital Seller AI
-- Run with supabase db push or psql

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- USERS (Supabase Auth provides a users table, but we keep a reference table)
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  name text,
  created_at timestamptz DEFAULT now()
);

-- COMPANIES
CREATE TABLE IF NOT EXISTS public.companies (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  owner_id uuid REFERENCES public.users(id),
  name text NOT NULL,
  segment text,
  city text,
  instagram text,
  google_maps_link text,
  whatsapp text,
  current_site text,
  description text,
  photos jsonb,
  created_at timestamptz DEFAULT now()
);

-- ANALYSIS (result from DIGITAL ANALYST AI)
CREATE TABLE IF NOT EXISTS public.analysis (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id uuid REFERENCES public.companies(id),
  digital_score int CHECK (digital_score BETWEEN 0 AND 100),
  report jsonb,
  created_at timestamptz DEFAULT now()
);

-- PROPOSALS (generated by PROPOSAL AI)
CREATE TABLE IF NOT EXISTS public.proposals (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id uuid REFERENCES public.companies(id),
  analyst_id uuid REFERENCES public.users(id),
  content jsonb,
  pdf_url text,
  created_at timestamptz DEFAULT now()
);

-- CLIENTS (closed deals)
CREATE TABLE IF NOT EXISTS public.clients (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id uuid REFERENCES public.companies(id),
  name text NOT NULL,
  phone text,
  value numeric,
  status text,
  notes text,
  closed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- CRM_STATUS enum and history
CREATE TYPE public.crm_stage AS ENUM (
  'NOVO_LEAD',
  'CONTATO_REALIZADO',
  'INTERESSADO',
  'PROPOSTA_ENVIADA',
  'FECHADO',
  'ENTREGUE'
);

CREATE TABLE IF NOT EXISTS public.crm_history (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id uuid REFERENCES public.clients(id),
  stage public.crm_stage,
  changed_at timestamptz DEFAULT now(),
  notes text
);

-- TEMPLATES (library of demo models)
CREATE TABLE IF NOT EXISTS public.templates (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text UNIQUE,
  structure jsonb,
  copy jsonb,
  palette jsonb,
  suggested_images jsonb
);

-- AI_HISTORY (log of AI calls)
CREATE TABLE IF NOT EXISTS public.ai_history (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.users(id),
  type text,
  prompt text,
  response jsonb,
  created_at timestamptz DEFAULT now()
);
